### ISSUE TITLE
JOIN PROJECT

### ISSUE THREAD

**Issue by nguyenhoang292211** [duchao11280/ProjectSE#8]
Xin chào, mình là Nguyễn Thị Minh Hoàng học lớp Quản lí dự án CNPM. Hiện tại mình là quản lý dự án App xây dựng chế độ dinh dưỡng, vì vậy hy vọng bạn có thể add mình vào project sớm nhất để chúng ta có thể hợp tác tốt hơn. Xin cảm ơn !!! =.=

**Comment by duchao11280** [comment]
ủa mình có add từ hôm t4 tuần trước rồi mà

**Comment by duchao11280** [comment]
![image](https://user-images.githubusercontent.com/30766129/113006393-8446eb80-919f-11eb-9bb1-ffae66c55cc8.png)
Check lại dùm mình nhé.

**Comment by nguyenhoang292211** [comment]
À do mình nhầm gmail  nên mình không thông báo bạn mời. Sorry bạn!

**Comment by nguyenhoang292211** [comment]
Phiền bạn có thể Invite mình vào project thêm lần nữa được không?? Tại một mới lấy lại mail nên lời mời trước quá hạn rồi. Cảm ơn bạn nhiều .

**Comment by duchao11280** [comment]
@nguyenhoang292211 rồi đó b

**Comment by nguyenhoang292211** [comment]
Team mình có lập group face ko bạn, add mk với để tiện trao đổi hơn. Hoặc bạn ib mình nha. 
Link facebook mk https://www.facebook.com/hoangnguyen.monokuro
